-- select a database to start  executation.
use mydatabase;


-- sample look of our data.
select * from mytable limit 10;


-- what is the total revenue generated by male vs female customers ?.
select gender ,sum(purchase_amount)  as sum_rev 
from mytable group by gender order by sum_rev;


-- which customers used a discount but still sspent more than the average purchase ammount ?.
select customer_id ,purchase_amount from mytable 
where discount_applied="Yes" and  
purchase_amount>(select avg(purchase_amount)from mytable);

-- which are the top 5 products with the highest average review rating ?.
select  item_purchased, avg(review_rating) as rev 
from mytable group by item_purchased order by rev desc limit 5 ;

 -- or 
 
select * from 
(select item_purchased ,avg(review_rating)as rev ,dense_rank() 
over (order by avg(review_rating)) as rnk 
from mytable group by item_purchased )t
 where rnk<=5 ;



-- compare the average purchase amount between shippings ?.
select shipping_type ,avg(purchase_amount)as rev ,dense_rank() 
over (order by a.vg(purchase_amount)) as rnk from mytable group by shipping_type ;


-- Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select subscription_status,avg(purchase_amount),sum(purchase_amount) from mytable group by  subscription_status; 



-- Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased, 100*round(sum(case when 
discount_applied="Yes" then 1 else 0 end)/count(*),2)  as discount_percentage
from mytable group by item_purchased order by  discount_percentage 
limit 5;




-- Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
alter table mytable add   segment_customer varchar(50);

update mytable set segment_customer=(case when previous_purchases<=15 then "New"
 when previous_purchases<=25 then "Returning"
 when previous_purchases<=50 then "Loyal"
else "" end);



-- What are the top 3 most purchased products within each category?

select category,item_purchased,per ,rnk from
(select category,item_purchased,count(customer_id) as per,row_number() 
over(partition by category order by count(customer_id) desc)  as rnk
from mytable group by category,item_purchased) t where rnk <=3 ;
 
 
 
 -- Are customers who are repeat buyers (more than 5 previous purchases) also 1ikely to subscribe?
select count(customer_id) as reparted_buyers,subscription_status 
from mytable where previous_purchases >=5
 group by subscription_status;
 
 
 
 -- What is the revenue contribution of each age group?
 select age_group ,sum(purchase_amount) as per from mytable  group by age_group order by  per desc;
 